[package]
name = "wiw"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.3"
env_logger = "0.11.3"
log = "0.4.22"
wgpu = "0.20.1"
pollster = "0.3.0"
bytemuck = { version = "1.16.1", features = ["derive"] }
glam = "0.28.0"
rand = "0.9.0-alpha.1"